package `in`.jiffycharge.gopower.model

import java.io.Serializable

data class ItemXXXXXXXX(
    val beginLocationDetails: String,
    val beginLocationLat: Double,
    val beginLocationLon: Double,
    val beginTime: Long,
    val borrowCabinetId: Int,
    val borrowCabinetStatusCode: String,
    val borrowChannel: Int,
    val borrowSellerId: Int,
    val borrowSysCode: String,
    val chargeRuleDesc: String,
    val checkDesc: String,
    val checkName: String,
    val checkTime: String,
    val cityId: String,
    val clientSource: String,
    val country: String,
    val createTime: String,
    val currency: String,
    val doingFeedbacks: List<DoingFeedbackX>,
    val endLocaitonDetails: String,
    val endLocationLat: Double,
    val endLocationLon: Double,
    val exchangeRateDesc: String,
    val finishTime: Long,
    val fitCoupon: FitCouponX,
    val id: Int,
    val isDeleted: Boolean,
    val officeId: Int,
    val orderCode: String,
    val outOrderId: String,
    val payOrderCode: String,
    val payPrice: Double,
    val payTime: String,
    val payType: String,
    val paymentMark: String,
    val pbCode: String,
    val pbId: Int,
    val price: Int,
    val ratePrice: Int,
    val returnCabinetId: Int,
    val returnChannel: Int,
    val returnSellerId: Int,
    val returnSysCode: String,
    val returnType: String,
    val rideTime: Int,
    val sellerName: String,
    val status: Int,
    val uid: Int,
    var userCouponId: Long
):Serializable